apiVersion: batch/v1
kind: Job
metadata:
  name: rmq-producer
  namespace: application
spec:
  template:
    spec:
      containers:
      - name: rmq-producer-01
        image: ashbourne1990/rabbitmq-direct-routing-example:latest
        command: ["python", "/app/producer/send.py", "rkey01", "10"]
        imagePullPolicy: Always
        env:
        - name: RMQ_USER
          valueFrom:
            secretKeyRef:
              name: rmq-credentials
              key: username
        - name: RMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rmq-credentials
              key: password
        - name: RMQ_EXCHANGE
          value: directex01
        - name: RMQ_HOST
          value: rabbitmq.rabbitmq.svc.cluster.local
      - name: rmq-producer-02
        image: ashbourne1990/rabbitmq-direct-routing-example:latest
        command: ["python", "/app/producer/send.py", "rkey02", "20"]
        imagePullPolicy: Always
        env:
        - name: RMQ_USER
          valueFrom:
            secretKeyRef:
              name: rmq-credentials
              key: username
        - name: RMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rmq-credentials
              key: password
        - name: RMQ_EXCHANGE
          value: directex01
        - name: RMQ_HOST
          value: rabbitmq.rabbitmq.svc.cluster.local
      restartPolicy: Never
  backoffLimit: 4